/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py:191: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  res = PandasDataFrame.from_items(items)
[info] Parsing spec ...
[info] Parsing succeeded
[info] Building synthesizer ...
[info] Synthesizing programs ...
[info] Solution not found!
[info] Synthesizing programs ...
====> run synthesize test_13.json
# num samples per layer: 4
                                        Title  year ...   SAP Scripting  SAP
0      Financial Accounting Assistant Manager  2003 ...             0.0  0.0
1      Financial Accounting Assistant Manager  2004 ...             0.0  1.0
2     Management Accounting Assistant Manager  2005 ...             0.0  2.0
3     Management Accounting Assistant Manager  2006 ...             0.0  3.0
4  Indirect Controlling and Reporting Analyst  2007 ...             0.0  4.0
5  Indirect Controlling and Reporting Analyst  2008 ...             0.0  4.0
6  Indirect Controlling and Reporting Analyst  2009 ...             0.0  4.0
7  Indirect Controlling and Reporting Analyst  2010 ...             1.0  4.0
8                  Finance Operations Analyst  2011 ...             1.0  4.0
9                  Finance Operations Analyst  2012 ...             1.0  4.0

[10 rows x 7 columns]
         c_color                                              c_x  c_y
0  SAP Scripting                  2011_Finance Operations Analyst  1.0
1            VBA  2008_Indirect Controlling and Reporting Analyst  1.0
2      MS Access  2007_Indirect Controlling and Reporting Analyst  0.0
3       MS Excel     2005_Management Accounting Assistant Manager  2.0
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 5


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF13838 <- RET_DF13836 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 7


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF13841 <- RET_DF13839 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 9


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF13844 <- RET_DF13842 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 7


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF13847 <- RET_DF13845 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 9


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF13858 <- RET_DF13856 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 7


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF13864 <- RET_DF13862 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 7


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21731 <- RET_DF21729 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 7


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21734 <- RET_DF21732 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 7


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21746 <- RET_DF21744 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 7


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21749 <- RET_DF21747 %>% mutate(cumsum=cumsum(.[[2]]))',)
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF32893 <- RET_DF32891 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF32912 <- RET_DF32910 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF32919 <- RET_DF32917 %>% mutate(cumsum=cumsum(.[[2]]))',)
[error] Error in interpreting spread...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF33616 <- RET_DF33614 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF33641 <- RET_DF33639 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF33661 <- RET_DF33659 %>% mutate(cumsum=cumsum(.[[1]]))',)
[error] Error in interpreting spread...

real	10m0.052s
user	9m16.719s
sys	0m15.670s
